### ISSUE TITLE
ImportError: cannot import name 'poly_nms_cuda'

### ISSUE THREAD

**Issue by PURE-melo** [dingjiansw101/AerialDetection#1]
Thanks for your code, but I met a mistake when training the model. 
ImportError: cannot import name 'poly_nms_cuda'
I have installed the environment according to INSTALL.md and my CUDA version is 9.0. How should I do to solve it?

**Comment by dingjiansw101** [comment]
Can you give me more details?

**Comment by dingjiansw101** [comment]
I add the "poly_nms" in the compile.sh. You can try to compile again.

**Comment by PURE-melo** [comment]
> I add the "poly_nms" in the compile.sh. You can try to compile again.

Thank you! The problem is solved.
