### ISSUE TITLE
cannot import name 'download_url_to_file' from 'torch.hub

### ISSUE THREAD

**Issue by prayagpawar** [dingjiansw101/AerialDetection#100]

**Comment by dingjiansw101** [comment]
https://github.com/open-mmlab/mmdetection/issues/7417  The same issue in mmdetection may help.

**Comment by prayagpawar** [comment]
i solved this error by removing underscore_ from _download_url_to_file function. So it should be download_url_to_file.
File location is /anaconda3/envs/(your env name)/lib/python3.7/site-packages/torch open hub.py
