### ISSUE TITLE
Where is the RPS RoI Align in this code?

### ISSUE THREAD

**Issue by Songyeyaosong** [dingjiansw101/AerialDetection#105]
The in_channels and out_channels of the rbbox_roi_extractor and the rbbox_head is 256，which is diffrent from the paper。

**Comment by dingjiansw101** [comment]
Please see the MXNet version code https://github.com/dingjiansw101/RoITransformer_DOTA/blob/9125055aed313dde7a68882e9931c9ea58c6f6ab/fpn/operator_cxx/psroi_rotated_align_ave.cu

In the mmdetection code, we use rotated roi align instead of rotated position sensitive roi align.

**Comment by Songyeyaosong** [comment]
> 
Thanks very much!
