### ISSUE TITLE
Running  ./compile.sh  gives an error

### ISSUE THREAD

**Issue by 237014845** [dingjiansw101/AerialDetection#2]
/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:314:13: note: declared here
 inline void deprecated_AT_CHECK() {}
             ^
In file included from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from src/poly_nms_cuda.cpp:1:
/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:339:40: warning: ‘void c10::detail::deprecated_AT_CHECK()’ is deprecated [-Wdeprecated-declarations]
     ::c10::detail::deprecated_AT_CHECK();                 \
                                        ^
src/poly_nms_cuda.cpp:3:23: note: in expansion of macro ‘AT_CHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
src/poly_nms_cuda.cpp:8:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(dets);
     ^
In file included from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from src/poly_nms_cuda.cpp:1:
/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:314:13: note: declared here
 inline void deprecated_AT_CHECK() {}
             ^
/usr/local/cuda/bin/nvcc -I/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include -I/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/kyq/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kyq/anaconda3/include/python3.7m -c src/poly_nms_kernel.cu -o build/temp.linux-x86_64-3.7/src/poly_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=poly_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.7
g++ -pthread -shared -B /home/kyq/anaconda3/compiler_compat -L/home/kyq/anaconda3/lib -Wl,-rpath=/home/kyq/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/poly_nms_cuda.o build/temp.linux-x86_64-3.7/src/poly_nms_kernel.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.7/poly_nms_cuda.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/poly_nms_cuda.cpython-37m-x86_64-linux-gnu.so -> 
Building cpu_nms...
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)

I used ubuntu16.04  cuda10    pytorch1.2

**Comment by dingjiansw101** [comment]
It seems a warning instead of an error. Can you run the training or testing code?

**Comment by 237014845** [comment]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 7, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 7, in <module>
    from mmdet.datasets import get_dataset
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/__init__.py", line 1, in <module>
    from mmdet.datasets import get_dataset
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/custom.py", line 11, in <module>
    from .custom import CustomDataset
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/extra_aug.py", line 5, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/__init__.py", line 4, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/__init__.py", line 4, in <module>
    from .loss import *  # noqa: F401, F403
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/loss/__init__.py", line 1, in <module>
    from .loss import *  # noqa: F401, F403
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/loss/__init__.py", line 1, in <module>
    from .losses import (weighted_nll_loss, weighted_cross_entropy,
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/loss/losses.py", line 7, in <module>
    from .losses import (weighted_nll_loss, weighted_cross_entropy,
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/core/loss/losses.py", line 7, in <module>
    from ...ops import sigmoid_focal_loss
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/__init__.py", line 1, in <module>
    from ...ops import sigmoid_focal_loss
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/__init__.py)
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/hs/hao/contextnet/AerialDetection-master/mmdet/ops/dcn/__init__.py)
Traceback (most recent call last):
  File "/home/hs/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hs/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hs/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=1', '/home/hs/hao/contextnet/AerialDetection-master/configs/DOTA/dota1_1024_train_val/retina_obb_r50_ctfpn2_2x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by dingjiansw101** [comment]
Can you pass the compile.sh in pytorch1.1?

**Comment by 237014845** [comment]
@dingjiansw101 Now it works, thanks

**Comment by daibin88** [comment]
> @dingjiansw101 Now it works, thanks

How to solve this issue?

**Comment by heyun1994** [comment]
@daibin88
I met the same problem.Have you solved it?
