### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by Hussni-V** [dingjiansw101/AerialDetection#24]
I have a dataset of coco format.  The annotations for the boxes are formatted as boxes = [x, y, w, h, theta]
I was looking at class DOTA1_5Dataset_v2(CocoDataset) so that I could get a sense of how to load the data. But I didn't see any theta and the boxes seem to have a format (x,y,w,h) instead of (x1,y1,x2,y2........). can I get some clarification on how & where theta comes in? Also what modifications I need to add to the dataset so that it can run with data of this format?

**Comment by dingjiansw101** [comment]
The DOTA1_5Dataset_v2(CocoDataset) use the COCO format. In the COCO format, the oriented bounding boxes are stored in mask format. 
If your data is in COCO format, you only need to change the CLASSES.
