### ISSUE TITLE
Question about inference speed.

### ISSUE THREAD

**Issue by ming71** [dingjiansw101/AerialDetection#27]
R-RetinaNet can reach 24 fps when I conduct evaluation on HRSC dataset.
However it dropped to 2fps when I inference on picture, why?
They should have been almost same, right?

**Comment by dingjiansw101** [comment]
On which picture you have 2fps? Different image resolution would influence the speed.

**Comment by ming71** [comment]
> On which picture you have 2fps? Different image resolution would influence the speed.

test on ICDAR dataset with res 1024*720

**Comment by dingjiansw101** [comment]
You can check if the processed pixel area per second is the same.

**Comment by mmoghadam11** [comment]
> You can check if the processed pixel area per second is the same.

where is it???
how can i check???
