### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by JonathanAndradeSilva** [dingjiansw101/AerialDetection#34]
Hi,

When I was training the model to a ten class problem, I found this error:

/content/AerialDetection/mmdet/models/rbbox_heads/rbbox_head.py in loss(self, cls_score, bbox_pred, labels, label_weights, bbox_targets, bbox_weights, reduce)
    164             pos_inds = labels > 0
    165             if self.reg_class_agnostic:
--> 166                 pos_bbox_pred = bbox_pred.view(bbox_pred.size(0), 5)[pos_inds]
    167             else:
    168                 pos_bbox_pred = bbox_pred.view(bbox_pred.size(0), -1,

RuntimeError: copy_if failed to synchronize: device-side assert triggered

May i ask how to solve?

**Comment by Yidann** [comment]
try to revise the num_classes=11 in your model config file.
