### ISSUE TITLE
Is there a part about larger separable convolution in the code?

### ISSUE THREAD

**Issue by wnynotfaker** [dingjiansw101/AerialDetection#37]
Hello, thank you very much for posting the code.In your paper, I learned that the features entered into RROI Learner are features processed by separable convolution.But the features entered into RROI Learner in the code seem to be the features obtained by FPN without separable convolution. I don’t know if I missed some code or you didn’t publish the separable convolution code.

Looking forward to your reply

**Comment by dingjiansw101** [comment]
Hi, this is an updated version. For separable convolution, you should refer to the original version. https://github.com/dingjiansw101/RoITransformer_DOTA
