### ISSUE TITLE
How are the positive and negative angles defined

### ISSUE THREAD

**Issue by wnynotfaker** [dingjiansw101/AerialDetection#38]
Hello, thank you very much for posting the code. I was reading “roi_align_rotated_kernel.cu” and found that you made changes when you did "Rotate by theta around the center and translate". My understanding of this is that your definition of positive and negative angles is opposite to RRPN. I don't know if I understand it right.

Looking forward to your reply

**Comment by chandlerbing65nm** [comment]
@wnynotfaker did you found out how they define angle in this repo?

**Comment by wnynotfaker** [comment]
> @wnynotfaker did you found out how they define angle in this repo?
I'm so sorry, it's been too long, I can't remember clearly.But my impression is that the positive and negative directions of the angles defined in this method are opposite to those of RRPN. Because the default angle of the horizontal frame is set to -90, if it is the same as the RRPN, it should be set to 90。@chandlerbing65nm
