### ISSUE TITLE
I am getting horizontal BB rather than Oriented and I can't change Batch Size

### ISSUE THREAD

**Issue by alaap001** [dingjiansw101/AerialDetection#4]
Hey,
I am trying to train on my custom dataset with 2 classes, both are rotated and are annotated in DOTA format. 

I tested using custom DOTA data and this cfg - **_faster_rcnn_RoITrans_r50_fpn_1x_dota_** to see results and got some txt files in work_dirs for each class, when I plotted the boxes with custom opencv I didn't get rotated bounding boxes but horizontal ones. I used test.py and set type = "OBB" while testing.

Now, I want rotated bounding boxes on my custom dataset, so do I have to use any other cfg file for that like - 
**_/DOTA1_5/faster_rcnn_obb_r50_fpn_1x_dota1_5.py_**
or the one I'm using will do the job of rotating. ?

Also is there any option to increase batch size or is it still 1 like the mxnet version of ROI_trans?
Thank you in advance. :)

**PS:  love your work, I've used ROI_trans on mxnet also which helped me to learn a great deal, I'm a student exploring better CV techniques.**

**Comment by LawrenceXia2008** [comment]
have you solved the problems?

**Comment by alaap001** [comment]
yes I did solved the orientation problem on my custom dataset, but still batch size is an issue. It is still 1 image at a time.

**Comment by Miki-lin** [comment]
I can not  cahange the batch_size too, where code can I modify to change the batch_size.
