### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

### ISSUE THREAD

**Issue by BlackHandguy** [dingjiansw101/AerialDetection#43]
我确实已经安装了mmcv，但还是发生了这个错误是怎么回事？
mmcv                      1.1.2                    pypi_0    pypi
mmdet                     0.6.0+a717a85             dev_0    <develop>
是版本不匹配的原因吗？

**Comment by SueeH** [comment]
请问是怎么解决的？我也遇到同样的问题。
![1111](https://user-images.githubusercontent.com/28698695/96245586-0e2c3f00-0fda-11eb-97c9-d62f14dc5a43.png)
