### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by ZIQIWANG-X** [dingjiansw101/AerialDetection#54]
when i ran **/AerialDetection/mmdet/ops/dcn$ python setup.py build_ext --inplace** in order to compile, a large amount of error codes appeared.
it says  **RuntimeError: Error compiling objects for extension**
my env is python 3.7,pytorch 1.6,cuda 10.2.
how could i do to solve the problem? thanks

**Comment by daibin88** [comment]
How to solve this issue?
