### ISSUE TITLE
技术细节

### ISSUE THREAD

**Issue by ZIQIWANG-X** [dingjiansw101/AerialDetection#55]
Excuse me,sir.This project is very helpful to me，thanks a lot.
However I still have abundant questions about the technical details,such as implementation method on DOTA by ‘faster-rcnn-h-obb’.May I have any related papers?：）
By the way，what is the reference source of the form in ‘model_zoo.md’？
Thank you again.

**Comment by dingjiansw101** [comment]
Hi, you can refer to the original DOTA paper. And there is a journal version of DOTA. We will release the arxiv recently.
