### ISSUE TITLE
./compile.sh error

### ISSUE THREAD

**Issue by QxGeng** [dingjiansw101/AerialDetection#56]
when i run ./compile.shh, there are some problems. Can you help me?

I have installed pytorch==1.1.0 cudatoolkit=10.0. 

Next is the code about error.
Building roi align op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building roi pool op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building roi align rotated op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building ps roi align rotated op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building nms op...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Building dcn...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building sigmoid focal loss op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building masked conv op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Building poly_nms op...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Building cpu_nms...
Traceback (most recent call last):
  File "setup_linux.py", line 18, in <module>
    from Cython.Distutils import build_ext
ModuleNotFoundError: No module named 'Cython'

I have installed torch numpy and cython. But there are problems.

**Comment by mmoghadam11** [comment]
> when i run ./compile.shh, there are some problems. Can you help me?
> 
> I have installed pytorch==1.1.0 cudatoolkit=10.0.
> 
> Next is the code about error.
> Building roi align op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building roi pool op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building roi align rotated op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building ps roi align rotated op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building nms op...
> Traceback (most recent call last):
> File "setup.py", line 4, in
> import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> Building dcn...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building sigmoid focal loss op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building masked conv op...
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> ModuleNotFoundError: No module named 'torch'
> Building poly_nms op...
> Traceback (most recent call last):
> File "setup.py", line 4, in
> import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> Building cpu_nms...
> Traceback (most recent call last):
> File "setup_linux.py", line 18, in
> from Cython.Distutils import build_ext
> ModuleNotFoundError: No module named 'Cython'
> 
> I have installed torch numpy and cython. But there are problems.

how did u dove it???
