### ISSUE TITLE
faster_rcnn_RoITrans_r50_fpn_1x_dota.py 训练结果比所给出的结果偏差比较大

### ISSUE THREAD

**Issue by Santiago24** [dingjiansw101/AerialDetection#58]
除更改DOTA数据集的路径， 配置文件与所给出的原配置一致，第一次训练faster_rcnn_RoITrans_r50_fpn_1x_dota.py实验结果比所给出的73.76高%2左右，第二次训练高%3左右。
GPU：2080ti.

**Comment by gewenchao** [comment]
请问一下，您训练和测试数据集图片分别是多少张
