### ISSUE TITLE
ModuleNotFoundError: No module named '_polyiou' .

### ISSUE THREAD

**Issue by aiboys** [dingjiansw101/AerialDetection#70]
When I ran `test.py`， there was somthing wrong with polyiou module [code](https://github.com/dingjiansw101/AerialDetection/blob/38692bbbc5619b3163f22cbb438e38c701b07936/DOTA_devkit/polyiou.py#L20)

**Comment by aiboys** [comment]
> When I ran `test.py`， there was somthing wrong with polyiou module [code](https://github.com/dingjiansw101/AerialDetection/blob/38692bbbc5619b3163f22cbb438e38c701b07936/DOTA_devkit/polyiou.py#L20)

I have solved it already.

**Comment by DuckJ** [comment]
@aiboys apt-get install swig？

**Comment by aiboys** [comment]
> @aiboys apt-get install swig？

yes，that‘s it.

**Comment by ghost** [comment]
> > When I ran `test.py`， there was somthing wrong with polyiou module [code](https://github.com/dingjiansw101/AerialDetection/blob/38692bbbc5619b3163f22cbb438e38c701b07936/DOTA_devkit/polyiou.py#L20)
> 
> I have solved it already.

Can you please elaborate your solution? I'm facing same issue

**Comment by aiboys** [comment]
> > > When I ran `test.py`， there was somthing wrong with polyiou module [code](https://github.com/dingjiansw101/AerialDetection/blob/38692bbbc5619b3163f22cbb438e38c701b07936/DOTA_devkit/polyiou.py#L20)
> > 
> > 
> > I have solved it already.
> 
> Can you please elaborate your solution? I'm facing same issue

oh, sry, it has been a long time. I cant remember the details, but you can try `apt-get install swig` or rebuild your local code

**Comment by Sidd1609** [comment]
I am also getting the same error, I installed swig but still getting this error
"ModuleNotFoundError: No module named '_polyiou'"
